### PR TITLE
Better deinterlacing

### PR DESCRIPTION
**Pull request by ljbade**
A rough working version of how I managed to get better deinterlacing with my local 3.0.x build.

Have not tried rebasing this on the master branch.

Likely could be improved by someone who is familar with rust, this is my first time touching rust so it more a case of getting it to compile was good enough.

It might be useful to have a setting to control whether the improved interlacing is enabled or not if people find it is too slow on older computers. The OpenGL deinterlacer might also provide a speed up if the CPU deinterlacer is too slow.

### CODE REVIEW

**Comment by russel** [comment]
I had believed that Freeview (DVB-T and DVB-T2 in UK) used 720p as SD and 1080p as HD, that 720i and 1080i were not used for broadcast. Is it the case that other DVB-T and DVB-T2 regions take a different view?

**Comment by ljbade** [comment]
Yeah in Australia they still use interlacing on a DVB-T signal as the digital system dates back to 2001.

The main HD channels are now all 1080i H.264 simulcast with SD for backwards compatibility with pre-H.264 boxes. Our SD channels are 576i MPEG-2 with lower resolutions for the few shopping channels.

Until a few years back there were some 720p and 576p channels with MPEG-2 but they were only used for secondary channels due to some strange regulation that required each network to have one "HD" channel that wasn't a simulcast of another SD channel. I think the broadcasters were worried about some old DVB-T boxes that wouldn't decode the higher resolutions. After the government scrapped that rule all the main channels switched to simulcast HD/SD.

There have been some experimental broadcasts of DVB-T2 with HEVC 1080p and 4K channels. I think there is a plan to eventually upgrade the digital TV system to that, perhaps using a second frequency to keep DVB-T for the old boxes.

I recall in New Zealand when I lived there during the digital TV launch in 2008 they also went for 1080i H.264 over DVB-T2 with secondary SD 576i H.264 channels.

I imagine there are a number of other countries still using interlacing.

**Comment by russel** [comment]
Hummm… I seem to have been under a misapprehension. It seems that UK Freeview reports 576i for SD channels and 1080i for HD channels. So the question is why haven't I seen any interlacing problems?

Update: Some Freeview UK channels report themselves as 576p.

**Comment by russel** [comment]
I need to do more work, but it does seem that for 576i and 1080i transmissions (it seems the Freeview channels switch between interlace and progressive so BBC HD channels are sometimes 1080i and sometimes 1080p) there is already a deinterlace element in the GStreamer pipeline. Hopefully it is not there for progressive transmissions. So I am wondering if we do not need to manually manipulate the pipeline itself just ensure the elements have the right options. It maybe that the dvbsrc element is not correctly conditioning the deinterlace element for your signal but it is OK for my signal.

**Comment by ljbade** [comment]
@russel I think it does automatically deinterlace, but the default mode for the deinterlace element is one of the lower quality options

On https://gstreamer.freedesktop.org/documentation/deinterlace/index.html?gi-language=c it says the default mode is `linear`.

Poking around in the gstreamer source code it also seems `playbin` always uses the CPU based `deinterlace`, whereas if you have OpenGL you can use `gldeinterlace` which might be useful for machines that have slower CPU but OpenGL GPU.

**Comment by russel** [comment]
@ljbade Experiments this morning much more successful than last evening, so I can confirm that using DVB-T/T2 in UK "linear" seems to be the default deinterlacing method. This would seem to imply we should have an option in the preferences (based on the list of sensible choices from the GStreamer documentation) and set it during the setup phase. This means somewhat different code to that that you have here. 
The GL issue is very different, and will necessitate a variant of the code you have – and will mean not allowing choosing an algorithm as for CPU based deinterlacing (grey it out as an option perhaps).
It seems that some broadcasts on HD channels report 1080i and other 1080p on the same channel. The question is whether the deinterlacing element copes with this.

Update: greedyh doesn't work for me, it just leads to a mess of lines, greedyl seems OK.

**Comment by russel** [comment]
@ljbade So I think the non-GL version of this is best handled by capturing the set up event of the deinterlace element in the playbin and setting the method on it as part of its set up. The method is obtained from the preferences, defaulting to linear. I have this coded up in master and it seems to work fine. Though it has to be said I can't tell any difference between linear and greedyl.

The GL version of this needs some work. The primary decision is where. The obvious place is to manipulate the pipeline in the glsinkbin to add the gldeinterlace element after the glupload element. However this puts the deinterlace very late in the pipeline compared to the non-GL case. However, perhaps that is fine? 
Not having the automatic deinterlace in playbin is easily handled using what is effectively the code you provided. I have this in place now.

**Comment by ljbade** [comment]
Sounds good. One thing I did notice with the GL deinterlace is that I had to add the gl colour space conversion element otherwise I got an error setting up the pipeline.

**Comment by russel** [comment]
The pipeline generated by the glsinkbin seems to be:
glupload → glcolorconvert → glcolorbalance → gtkglsink
the trick is going to be how to insert the glinterlace element just after the glupload and get the right source/sink pads connected. It would be nice if I could just condition the glsinkbin and it did it, but I fear it is going tohave to be a bit more manual.

**Comment by russel** [comment]
On advice, it is best not to tinker with the pipeline in the glsinkbin, but instead just to use a new bin with the gldeinterlace and gtkglsink elements in it as the sink for the glsinkbin. Now done and seems to be working, along with user preferences for the method selection. The change set is currently only on master, I guess is could be cherry picked onto the v3.0.x branch to add it to the v3.0.10 that ought to be released soon.

**Comment by russel** [comment]
Although this merge request has prompted a lot of thinking, and changes to the codebase, it is not right to merge it as it stands. The ideas behind this changeset have been implemented somewhat differently to the way presented here. See https://github.com/Me-TV/Me-TV/commit/71d58839ab5b539fa3d9de57305a7b36031ff92c

**Comment by russel** [comment]
I am being informed by the GStreamer folk that using GL will not necessarily improve performance, that not using GL in a GStreamer pipeline will usually lead to better performance!

**Comment by ljbade** [comment]
@russel really? It seems to use less CPU on my computer

**Comment by russel** [comment]
@ljbade  Excellent. The GStreamer folk are saying that some GL implementation with GTK+ 3 still require CPU rendering, I think I see this with my Debian Sid/OpenGL/GStreamer platform – GL takes more CPU than non-GL. Apparently all the problems are fixed in GTK+ 4 so GL should always be faster with less CPU usage.

Have you been able to try the 3.0.10 release or master?

**Comment by ljbade** [comment]
@russel not yet I will test it later today

**Comment by ljbade** [comment]
I tested 3.0.10 and everything works well

**Comment by russel** [comment]
@ljbade  Great news. Thanks for all your work on creating the merge request. Although your code was not used directly, it was very, very useful in guiding me to create the code I did.

I am still wondering why the default interlace behaviour works for me here with Freeview in the UK, but doesn't for you. I shall have to investigate further, but more at leisure. :-)

**Pull request closed without merging**
