### PR TITLE
Unhardcode launcher icon path

### PR DESCRIPTION
**Pull request by palob**
Since the icon already is installed to `.../share/pixmaps`, a location compliant with [freedesktop.org standards](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html) you don't need to specify the full icon path (neither the file type extension) in the launcher. 
The icon will be found anyway by DEs adhering to the standards which all DEs I know do (GNOME, KDE, Xfce, MATE, Cinnamon, Budgie, LXDE, LXQt, Pantheon, Deepin, Lumina, Enlightenment).

Cf. this [example `.desktop` launcher](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#example) presented in the freedesktop.org documentation.

This facilitates icon theming and the DE to pick up differently sized icons in case you provide them in ``/share/icons/hicolor/<size>/apps``.

### CODE REVIEW

**Comment by russel** [comment]
Thanks for sending in this merge request, and educating me in the process. Much appreciated.

**Comment by palob** [comment]
Thank you for merging.

**Comment by whittet** [comment]
What is the impact if someone runs the app outside of a window manager?

**Comment by palob** [comment]
The impact of which?

**Pull request merged**
